name: Setup ChatGPT CLI
description: Setup ChatGPT CLI
branding:
  icon: book
  color: orange
runs:
  using: "composite"
  steps:
    - if: runner.os == 'Linux'
      shell: bash
      env:
        GH_ACTION_REF: ${{ github.action_ref || github.ref_name }}
      run: |
        sudo curl -Ls https://github.com/kezhenxu94/chatgpt-java/releases/download/${{ env.GH_ACTION_REF }}/chatgpt-cli.ubuntu -o /usr/local/bin/chatgpt
        sudo chmod +x /usr/local/bin/chatgpt
    - if: runner.os == 'macOS'
      shell: bash
      env:
        GH_ACTION_REF: ${{ github.action_ref || github.ref_name }}
      run: |
        sudo curl -Ls https://github.com/kezhenxu94/chatgpt-java/releases/download/${{ env.GH_ACTION_REF }}/chatgpt-cli.macos -o /usr/local/bin/chatgpt
        sudo chmod +x /usr/local/bin/chatgpt
