name: Setup ChatGPT CLI
description: Setup ChatGPT CLI
branding:
  icon: book
  color: orange
runs:
  using: "composite"
  steps:
    - if: runner.os == 'Linux'
      shell: bash
      run: |
        curl -Ls https://github.com/kezhenxu94/chatgpt-java/releases/download/${{ github.action_ref }}/chatgpt-cli.ubuntu -o chatgpt-cli
        sudo install chatgpt-cli /usr/local/bin/chatgpt
    - if: runner.os == 'macOS'
      shell: bash
      run: |
        curl -Ls https://github.com/kezhenxu94/chatgpt-java/releases/download/${{ github.action_ref }}/chatgpt-cli.macos -o chatgpt-cli
        sudo install chatgpt-cli /usr/local/bin/chatgpt
